// @ts-ignore Generated by OpenNext during the Cloudflare build.
import handler from "./.open-next/worker.js";
// @ts-ignore Resolved by the Cloudflare Workers runtime.
import { DurableObject } from "cloudflare:workers";

type Reservation = { bytes: number; expiresAt: number };
type CoordinatorState = {
  initialized: boolean;
  mediaBytes: number;
  quotaBytes: number | null;
  reservations: Record<string, Reservation>;
};

export class StorageQuotaCoordinator extends DurableObject {
  private readonly storageContext: { storage: { transaction<T>(callback: (storage: { get(key: string): Promise<CoordinatorState | undefined>; put(key: string, value: CoordinatorState): Promise<void> }) => Promise<T>): Promise<T> } };

  constructor(ctx: typeof StorageQuotaCoordinator.prototype.storageContext, env: unknown) {
    super(ctx, env);
    this.storageContext = ctx;
  }

  async fetch(request: Request): Promise<Response> {
    const payload = await request.json() as Record<string, unknown>;
    const action = new URL(request.url).pathname;
    return this.storageContext.storage.transaction(async (storage) => {
      const current = await storage.get("quota-state") ?? {
        initialized: false,
        mediaBytes: 0,
        quotaBytes: null,
        reservations: {}
      };
      const now = Date.now();
      current.reservations = Object.fromEntries(Object.entries(current.reservations).filter(([, item]) => item.expiresAt > now));

      if (action === "/reserve") {
        const baseline = Number(payload.mediaBytes);
        const stateBytes = Number(payload.siteDataBytes);
        const delta = Number(payload.deltaBytes);
        if (![baseline, stateBytes, delta].every(Number.isSafeInteger) || baseline < 0 || stateBytes < 0) {
          return Response.json({ error: "Invalid storage reservation." }, { status: 400 });
        }
        if (!current.initialized) {
          current.initialized = true;
          current.mediaBytes = baseline;
          current.quotaBytes = typeof payload.quotaBytes === "number" ? payload.quotaBytes : null;
        }
        current.mediaBytes = Math.max(current.mediaBytes, baseline);
        const reservedBytes = Object.values(current.reservations).reduce((sum, item) => sum + Math.max(0, item.bytes), 0);
        const proposedMedia = current.mediaBytes + reservedBytes + delta;
        if ((delta > 0 || payload.addsMedia === true) && current.quotaBytes !== null && stateBytes + proposedMedia > current.quotaBytes) {
          await storage.put("quota-state", current);
          return Response.json({ error: "存储空间不足。请删除媒体文件或联系超级管理员提高全站额度。" }, { status: 413 });
        }
        const token = crypto.randomUUID();
        current.reservations[token] = { bytes: delta, expiresAt: now + 120_000 };
        await storage.put("quota-state", current);
        return Response.json({ token });
      }

      if (action === "/complete" || action === "/cancel") {
        const token = String(payload.token ?? "");
        const reservation = current.reservations[token];
        if (!reservation) return Response.json({ error: "Storage reservation expired." }, { status: 409 });
        if (action === "/complete") current.mediaBytes = Math.max(0, current.mediaBytes + reservation.bytes);
        delete current.reservations[token];
        await storage.put("quota-state", current);
        return Response.json({ ok: true });
      }

      if (action === "/limit") {
        const quota = payload.quotaBytes;
        const baseline = Number(payload.mediaBytes);
        if ((quota !== null && (typeof quota !== "number" || !Number.isSafeInteger(quota) || quota <= 0)) || !Number.isSafeInteger(baseline) || baseline < 0) {
          return Response.json({ error: "Invalid storage quota." }, { status: 400 });
        }
        current.initialized = true;
        current.mediaBytes = Math.max(current.mediaBytes, baseline);
        current.quotaBytes = quota as number | null;
        await storage.put("quota-state", current);
        return Response.json({ ok: true });
      }

      return Response.json({ error: "Unknown action." }, { status: 404 });
    });
  }
}

export default handler;
