'use client';
/* eslint-disable @next/next/no-img-element */
import {useState} from 'react';
import {t} from '@/lib/i18n';
import {catalogTypes,isCollection,isPublishedProduct} from '@/lib/catalog';
import type {ProductCategory,LocaleCode} from '@/types/site';
export function ProductCatalog({products,locale,initialCategory=''}:{products:ProductCategory[];locale:LocaleCode;initialCategory?:string}){
 const zh=locale==='zh';const [category,setCategory]=useState(initialCategory);const [type,setType]=useState('');const [query,setQuery]=useState('');const [limit,setLimit]=useState(24);
 const entries=products.filter(p=>!isCollection(p)&&isPublishedProduct(p));const inCategory=entries.filter(p=>!category||p.categorySlugs?.includes(category));const types=[...new Set(inCategory.map(p=>p.productType).filter(Boolean))] as string[];
 const found=inCategory.filter(p=>(!type||p.productType===type)&&`${p.name.en} ${p.name.zh} ${p.model??''}`.toLowerCase().includes(query.trim().toLowerCase()));
 return <section className="yuva-catalog"><div className="yuva-filters"><label>{zh?'系列':'Collection'}<select value={category} onChange={e=>{setCategory(e.target.value);setType('');setLimit(24)}}><option value="">{zh?'全部产品':'All products'}</option>{[['lips','唇妆','Lips'],['eyes','眼妆','Eyes'],['face','面部彩妆','Face']].filter(([key])=>entries.some(p=>p.categorySlugs?.includes(key))).map(([key,cn,en])=><option key={key} value={key}>{zh?cn:en}</option>)}</select></label><label>{zh?'产品类别':'Product type'}<select value={type} onChange={e=>{setType(e.target.value);setLimit(24)}}><option value="">{zh?'全部类别':'All types'}</option>{types.map(key=><option key={key} value={key}>{catalogTypes[key]?.[zh?'zh':'en']??key}</option>)}</select></label><label>{zh?'搜索产品或型号':'Search products or model'}<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setLimit(24)}} placeholder={zh?'例如：唇釉、C10':'e.g. lip tint, C10'}/></label></div><p aria-live="polite">{found.length} {zh?'款产品':'products'}</p><div className="yuva-product-grid">{found.slice(0,limit).map(p=><a className="yuva-product-card" key={p.id??p.slug} href={`/${locale}/products/${p.slug}`}><div><img src={p.thumbnailUrl||p.imageUrl} alt={t(p.name,locale)} loading="lazy" width="640" height="640"/></div><small>{catalogTypes[p.productType??'']?.[zh?'zh':'en']} {p.model?`/ ${p.model}`:''}</small><h2>{t(p.name,locale)}</h2><span>{zh?'查看产品':'Explore product'} ↗</span></a>)}</div>{!found.length?<p>{zh?'未找到匹配产品，请调整搜索条件。':'No products found. Try another search.'}</p>:null}{found.length>limit?<button className="yuva-button" onClick={()=>setLimit(limit+24)}>{zh?'加载更多':'Load more'}</button>:null}</section>
}
export function ProductGallery({product:p,locale}:{product:ProductCategory;locale:LocaleCode}){const images=[...(p.imageUrl?[{url:p.imageUrl,alt:p.name}]:[]),...(p.gallery??[]).filter(im=>im.url!==p.imageUrl)].slice(0,7);if(!images.length)images.push({url:'',alt:p.name});const [active,setActive]=useState(0);return <div className="yuva-gallery"><a href={images[active].url} target="_blank" rel="noreferrer" aria-label={locale==='zh'?'查看完整图片':'View full image'}><img className="yuva-gallery-main" src={images[active].url} alt={t(images[active].alt??p.name,locale)} width="1200" height="1200"/></a>{images.length>1?<div className="yuva-gallery-thumbs">{images.map((im,i)=><button key={im.url} onClick={()=>setActive(i)} aria-pressed={i===active} aria-label={`${locale==='zh'?'产品图片':'Product image'} ${i+1}`}><img src={im.url} alt="" width="90" height="90" loading="lazy"/></button>)}</div>:null}</div>}
export function ProductShades({product:p,locale}:{product:ProductCategory;locale:LocaleCode}){const [more,setMore]=useState(false);const shades=p.shades??[];if(!shades.length)return null;const zh=locale==='zh';return <section className="yuva-shades"><h2>{zh?'色号与款式参考':'Shade & variant references'}</h2><p>{zh?'图片保留原包装及配色；以下序号仅用于浏览，正式色号与可供款式请询盘确认。':'Original packaging and colors are shown. Reference numbers are for browsing; confirm shade codes and availability with us.'}</p><div className="yuva-shade-grid">{shades.slice(0,more?shades.length:6).map((s,i)=><figure key={s.url}><a href={s.url} target="_blank" rel="noreferrer"><img src={s.url} alt={`${t(p.name,locale)} — ${s.label}`} loading="lazy" width="800" height="800"/></a><figcaption>{zh?`参考 ${i+1}`:s.label}</figcaption></figure>)}</div>{shades.length>6?<button className="yuva-button" onClick={()=>setMore(!more)} aria-expanded={more}>{more?(zh?'收起':'Show less'):(zh?`查看全部 ${shades.length} 张参考图`:`View all ${shades.length} references`)}</button>:null}</section>}
