/* eslint-disable @next/next/no-img-element */
import {ProductCatalog,ProductGallery,ProductShades} from '@/components/ProductCatalog';
import {catalogTypes,isPublishedProduct} from '@/lib/catalog';
import { ArticleContent } from '@/components/ArticleContent';
import { RfqForm } from '@/components/RfqForm';
import { t } from '@/lib/i18n';
import type { AdminState,LocaleCode,ProductCategory,SitePage } from '@/types/site';
const A='/assets/current-template/';
export function YuvaProducts({state,locale,initialCategory=''}:{state:AdminState;locale:LocaleCode;initialCategory?:string}){const zh=locale==='zh';const collection=state.products.find(p=>p.slug===initialCategory);return <main className="yuva-page"><div className="yuva-intro"><p className="yuva-eyebrow">{zh?'彩妆产品':'OUR COLOR COLLECTION'}</p><h1>{collection?t(collection.name,locale):(zh?'寻找您的下一抹色彩。':'Find your expression.')}</h1><p>{zh?'探索产品、包装和配色，与我们沟通您的需求。':'Explore products, packaging and color. Share your next collection with us.'}</p></div><ProductCatalog products={state.products.filter(isPublishedProduct).map(({gallery:_gallery,shades:_shades,...p})=>p)} locale={locale} initialCategory={initialCategory}/></main>}
export function YuvaProduct({product:p,locale}:{product:ProductCategory;locale:LocaleCode}){const zh=locale==='zh';return <main className="yuva-page"><section className="yuva-real-detail"><ProductGallery product={p} locale={locale}/><div><p className="yuva-eyebrow">{catalogTypes[p.productType??'']?.[zh?'zh':'en']??(zh?'产品系列':'PRODUCT COLLECTION')}</p><h1>{t(p.name,locale)}</h1>{p.model?<p>{zh?'型号':'Model'}: {p.model}</p>:null}<p>{t(p.summary,locale)}</p><a className="yuva-button" href="#rfq">{zh?'询问产品与样品':'Enquire about this product'} ↗</a><p><small>{zh?'图片展示原包装，色号、配方和包材可供方案请询盘确认。':'Images show original packaging. Confirm available shades, formulas and packaging when enquiring.'}</small></p><a href={`/${locale}/products`}>{zh?'浏览全部产品':'Browse all products'} →</a></div></section><ProductShades product={p} locale={locale}/><YuvaContact locale={locale} embedded productName={`${t(p.name,locale)}${p.model?' / '+p.model:''} [${p.slug}]`}/></main>}
export function YuvaContact({locale,embedded=false,productName=""}:{locale:LocaleCode;embedded?:boolean;productName?:string}){const zh=locale==='zh';const body=<section className="yuva-contact" id="rfq"><div><p className="yuva-eyebrow">{zh?'新灵感，新可能':'NEW IDEAS. NEW POSSIBILITIES.'}</p>{embedded?<h2>{zh?'开启您的\n美妆故事。':'Begin your\nbeauty story.'}</h2>:<h1>{zh?'开启您的\n美妆故事。':'Begin your\nbeauty story.'}</h1>}<p>{zh?'从唇妆、眼妆到底妆，与我们分享产品构想。':'From lips and eyes to complexion. Tell us what you imagine.'}</p><div><p><strong>金华市纤烁化妆品有限公司</strong><br/>{zh?'浙江省金华市兰溪市横溪镇兰浦西路49号':'No. 49 Lanpu West Road, Hengxi Town, Lanxi, Jinhua, Zhejiang, China'}</p><p><strong>YUCHUANG BIOTECHNOLOGY INDONESIA</strong><br/>Landmark Pluit Tower E7, 6th Floor, V22, Jalan Pluit Selatan Raya, Pluit, Penjaringan, North Jakarta, Indonesia</p><p><a href={`/${locale}/pages/about`}>{zh?'公司登记信息与完整地址':'Company details and full addresses'} →</a></p></div><a href={`/${locale}/pages/privacy`}>{zh?'提交前阅读询盘隐私说明':'Read our inquiry privacy notice'}</a></div><RfqForm locale={locale} productName={productName}/></section>;return embedded?body:<main className="yuva-page">{body}</main>}
export function YuvaStory({page,locale}:{page:SitePage;locale:LocaleCode}){const title=t(page.title,locale);const body=<ArticleContent body={t(page.body,locale)}/>;if(page.slug==='oem-odm')return <main className="yuva-page"><section className="yuva-oem"><img src={A+'palette.webp'} alt="Illustrative eyeshadow palette"/><div><p className="yuva-eyebrow">OEM / ODM</p><h1>{title}</h1>{body}<a className="yuva-button" href={`/${locale}/contact`}>{locale==='zh'?'提交产品需求':'Share your brief'} ↗</a></div></section><section className="yuva-story-hero"><img src={A+'craft.webp'} alt="Illustrative cosmetics production concept" loading="lazy"/><h2>{locale==='zh'?'一起，成就彩妆。':'Beauty brands. Made together.'}</h2></section></main>;
if(page.slug==='factories')return <main className="yuva-page"><section className="yuva-intro"><p className="yuva-eyebrow">CHINA & INDONESIA</p><h1>{title}</h1></section>{[['china','Jinhua, China','金华市纤烁化妆品有限公司'],['indonesia','Jakarta, Indonesia','YUCHUANG BIOTECHNOLOGY INDONESIA']].map(([img,title,company])=><section className="yuva-location yuva-factory-panorama" id={img} key={img}><img src={A+img+'.webp'} alt={title+' factory concept illustration'}/><div><h3>{title}</h3><p>{company}</p><small>{locale==='zh'?'工厂概念示意，非实景照片':'Illustrative concept. Not a photograph of the actual premises.'}</small></div></section>)}<section className="yuva-story-copy">{body}</section></main>;
return <main className="yuva-page">{page.slug==='privacy'?<div className="yuva-intro"><h1>{title}</h1></div>:<section className="yuva-story-hero"><img src={A+(page.slug==='research'?'pigment':'craft')+'.webp'} alt="Illustrative cosmetics concept"/><h1>{title}</h1></section>}<section className="yuva-story-copy">{body}</section></main>}
