/* eslint-disable @next/next/no-img-element */
import { ArticleContent } from '@/components/ArticleContent';
import { RfqForm } from '@/components/RfqForm';
import { t } from '@/lib/i18n';
import type { AdminState,LocaleCode,ProductCategory,SitePage } from '@/types/site';
const A='/assets/current-template/';
export function YuvaProducts({state,locale}:{state:AdminState;locale:LocaleCode}){return <main className="yuva-page"><div className="yuva-intro"><p className="yuva-eyebrow">{locale==='zh'?'彩妆系列':'COLOR CREATES NEW POSSIBILITIES'}</p><h1>{locale==='zh'?'您的下一抹色彩。':'Find your expression.'}</h1></div>{state.products.map((p,i)=><a className="yuva-chapter" key={p.slug} href={`/${locale}/products/${p.slug}`}><img src={p.imageUrl} alt={t(p.name,locale)} loading={i?'lazy':'eager'}/><span className="yuva-chapter-index">0{i+1}</span><h2>{t(p.name,locale)}</h2><p>{t(p.summary,locale)}</p><span className="yuva-chapter-arrow">↗</span></a>)}</main>}
export function YuvaProduct({product:p,locale}:{product:ProductCategory;locale:LocaleCode}){const zh=locale==='zh';return <main className="yuva-page"><section className="yuva-detail"><img src={p.imageUrl} alt={t(p.name,locale)+' — illustrative concept'}/><div><p className="yuva-eyebrow">{t(p.name,locale)} / {zh?'概念系列':'CONCEPT COLLECTION'}</p><h1>{zh?'不止于\n一抹色彩。':'More than\na color.'}</h1><p>{t(p.summary,locale)}</p></div><a className="yuva-button" href="#rfq">{zh?'沟通样品需求':'Request a sample'} ↗</a></section><section className="yuva-specs"><div><h2>{zh?'为您的品牌':'For your brand'}</h2><ul>{t(p.applications,locale).map(x=><li key={x}>{x}</li>)}</ul></div><div><h2>{zh?'一起定义细节':'Consider every detail'}</h2><ul>{p.specs.map(x=><li key={x}>{x}</li>)}</ul><p>{zh?'色号、配方、包材与订单条件须按项目确认。':'Shades, formulas, packaging and order terms are confirmed for each project.'}</p></div></section><YuvaContact locale={locale} embedded/></main>}
export function YuvaContact({locale,embedded=false}:{locale:LocaleCode;embedded?:boolean}){const zh=locale==='zh';const body=<section className="yuva-contact" id="rfq"><div><p className="yuva-eyebrow">{zh?'新灵感，新可能':'NEW IDEAS. NEW POSSIBILITIES.'}</p>{embedded?<h2>{zh?'开启您的\n美妆故事。':'Begin your\nbeauty story.'}</h2>:<h1>{zh?'开启您的\n美妆故事。':'Begin your\nbeauty story.'}</h1>}<p>{zh?'从唇妆、眼妆到底妆，与我们分享产品构想。':'From lips and eyes to complexion. Tell us what you imagine.'}</p><p>Jinhua, China<br/>Indonesia</p><a href={`/${locale}/pages/privacy`}>{zh?'提交前阅读询盘隐私说明':'Read our inquiry privacy notice'}</a></div><RfqForm locale={locale}/></section>;return embedded?body:<main className="yuva-page">{body}</main>}
export function YuvaStory({page,locale}:{page:SitePage;locale:LocaleCode}){const title=t(page.title,locale);const body=<ArticleContent body={t(page.body,locale)}/>;if(page.slug==='oem-odm')return <main className="yuva-page"><section className="yuva-oem"><img src={A+'palette.webp'} alt="Illustrative eyeshadow palette"/><div><p className="yuva-eyebrow">OEM / ODM</p><h1>{title}</h1>{body}<a className="yuva-button" href={`/${locale}/contact`}>{locale==='zh'?'提交产品需求':'Share your brief'} ↗</a></div></section><section className="yuva-story-hero"><img src={A+'craft.webp'} alt="Illustrative cosmetics production concept" loading="lazy"/><h2>{locale==='zh'?'一起，成就彩妆。':'Beauty brands. Made together.'}</h2></section></main>;
if(page.slug==='factories')return <main className="yuva-page"><section className="yuva-intro"><p className="yuva-eyebrow">CHINA & INDONESIA</p><h1>{title}</h1></section>{[['china','Jinhua, China','金华纤烁化妆品有限公司'],['indonesia','Indonesia','Yuvacosmetics']].map(([img,title,company])=><section className="yuva-location yuva-factory-panorama" id={img} key={img}><img src={A+img+'.webp'} alt={title+' factory concept illustration'}/><div><h3>{title}</h3><p>{company}</p><small>{locale==='zh'?'工厂概念示意，非实景照片':'Illustrative concept. Not a photograph of the actual premises.'}</small></div></section>)}<section className="yuva-story-copy">{body}</section></main>;
return <main className="yuva-page">{page.slug==='privacy'?<div className="yuva-intro"><h1>{title}</h1></div>:<section className="yuva-story-hero"><img src={A+(page.slug==='research'?'pigment':'craft')+'.webp'} alt="Illustrative cosmetics concept"/><h1>{title}</h1></section>}<section className="yuva-story-copy">{body}</section></main>}
