import fs from 'node:fs';
import assert from 'node:assert/strict';
const base=process.argv[2]||'http://127.0.0.1:3024';
const evidence=process.argv[3]||'05_测试与交付/本地接口验收.json';
const password=process.env.YUVA_TEST_PASSWORD;
assert(password);const checks=[];let cookie;
async function req(path,options={}){return fetch(base+path,{...options,headers:{...(cookie?{Cookie:cookie}:{}),...options.headers}})}
async function check(name,fn){try{await fn();checks.push({name,pass:true});console.log('PASS',name)}catch(e){checks.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message);throw e}finally{fs.writeFileSync(evidence,JSON.stringify({base,time:new Date().toISOString(),checks},null,2))}}
for(const path of ['/en','/en/products','/en/products/lips','/en/products/eyes','/en/products/face','/en/pages/oem-odm','/en/pages/about','/en/pages/factories','/en/pages/research','/en/contact','/zh','/en/pages/privacy','/robots.txt','/sitemap.xml'])await check(path,async()=>{const r=await req(path);assert.equal(r.status,200);const text=await r.text();assert(!/KeyproTools|carbide|铣刀/.test(text));});
await check('Admin unauthorized protection',async()=>assert.equal((await req('/api/admin/state')).status,401));
await check('Authorized admin login',async()=>{const r=await req('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'437991663@qq.com',password})});assert.equal(r.status,200);cookie=r.headers.get('set-cookie')?.split(';')[0];assert(cookie);});
let state;await check('CMS clean seed and safe password response',async()=>{state=await(await req('/api/admin/state')).json();assert.equal(state.users.length,1);assert.equal(state.pages.length,5);assert.equal(state.products.length,3);assert.equal(state.contactChannels.length,0);assert(!JSON.stringify(state).includes(password));assert(!state.users.some(u=>u.passwordHash));});
let leadId;await check('Inquiry persisted and read back',async()=>{const r=await req('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName:'Codex QA 验收',company:'Internal test',productType:'Lipstick test — ignore',quantity:'1000',email:'qa@example.com',message:'Deployment acceptance test; not a commercial inquiry.',locale:'en'})});assert.equal(r.status,200);leadId=(await r.json()).lead.id;for(let i=0;i<15;i++){state=await(await req('/api/admin/state')).json();if(state.leads.some(l=>l.id===leadId))return;await new Promise(r=>setTimeout(r,4000));}throw Error('Inquiry not read back after propagation window')});
await check('CMS settings persistence',async()=>{const r=await req('/api/admin/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});assert.equal(r.status,200);const saved=await r.json();for(let i=0;i<25;i++){const read=await(await req('/api/admin/state')).json();if(read.updatedAt===saved.updatedAt){assert.equal(read.siteSettings.title,'Yuvacosmetics');assert(read.leads.some(l=>l.id===leadId));return;}await new Promise(r=>setTimeout(r,4000));}throw Error('Saved CMS version not visible after propagation window');});
await check('Media upload and retrieval',async()=>{const form=new FormData();form.set('file',new Blob(['Yuvacosmetics QA media verification'],{type:'text/plain'}),'验收测试.txt');const r=await req('/api/admin/upload',{method:'POST',body:form});assert.equal(r.status,200);const f=(await r.json()).file;for(let i=0;i<15;i++){const get=await req(f.url);if(get.status===200){assert.equal(await get.text(),'Yuvacosmetics QA media verification');return;}await new Promise(r=>setTimeout(r,4000));}throw Error('Media retrieval propagation timeout');});
console.log('Acceptance complete',checks.length);
