import fs from 'node:fs';
import assert from 'node:assert/strict';
const base=process.argv[2],source=process.argv[3],evidence=process.argv[4];const catalog=JSON.parse(fs.readFileSync(source));const checks=[];
async function check(name,run){try{await run();checks.push({name,pass:true});console.log('PASS',name)}catch(e){checks.push({name,pass:false,error:e.message});throw e}finally{fs.writeFileSync(evidence,JSON.stringify({base,time:new Date().toISOString(),checks},null,2));}}
await check('60 published products, one draft, unique identifiers',async()=>{assert.equal(catalog.filter(p=>p.status==='published').length,60);assert.equal(catalog.filter(p=>p.status==='draft').length,1);assert.equal(new Set(catalog.map(p=>p.slug)).size,catalog.length);for(const p of catalog.filter(p=>p.status==='published')){assert(p.categorySlugs.length);assert(p.gallery.length<=7);assert(p.imageUrl.startsWith('https://media.yuvacosmetics.com/'));assert.equal(new Set(p.shades.map(s=>s.url)).size,p.shades.length);}});
for(const path of ['/en','/en/products','/en/products/lips','/en/products/eyes','/en/products/face','/zh/products','/en/pages/factories'])await check(path,async()=>{const r=await fetch(base+path);assert.equal(r.status,200);const html=await r.text();assert(!html.includes('nail-gel-review'));if(path==='/en/products')assert(html.includes('Search products or model'));});
for(const p of catalog.filter(p=>p.status==='published'))await check('product '+p.slug,async()=>{const r=await fetch(base+'/en/products/'+p.slug);assert.equal(r.status,200);const html=await r.text();assert(html.includes(p.name.en.replaceAll('&','&amp;'))||html.includes(p.name.en));assert(html.includes(p.imageUrl));assert(!html.includes('CONCEPT COLLECTION'));assert(html.includes(p.slug));});
await check('draft hidden and missing product returns 404',async()=>{for(const slug of ['nail-gel-review','catalog-nonexistent'])assert.equal((await fetch(base+'/en/products/'+slug)).status,404);const sitemap=await(await fetch(base+'/sitemap.xml')).text();assert(!sitemap.includes('nail-gel-review'));for(const p of catalog.filter(p=>p.status==='published'))assert(sitemap.includes('/en/products/'+p.slug));});
await check('anonymous media write denied',async()=>assert.equal((await fetch(base+'/api/admin/upload',{method:'POST'})).status,401));
console.log('CATALOG PASS',checks.length);
