/* eslint-disable @next/next/no-img-element */
import { HomeNavigationShell } from '@/components/PublicSiteShell';
import { HeroPosterCarousel } from '@/components/HeroPosterCarousel';
import { RfqForm } from '@/components/RfqForm';
import { t } from '@/lib/i18n';
import type { AdminState, LocaleCode, HomeSectionKey } from '@/types/site';
const A='/assets/current-template/';
export function ActiveTemplate({locale,state}:{locale:LocaleCode;state:AdminState}){
 const s=state.templateSettings; const zh=locale==='zh';
 const sections:{key:HomeSectionKey;node:React.ReactNode}[]=[
 {key:'navigation',node:<HomeNavigationShell brandName={state.siteSettings.title} ctaLabel={zh?'开启品牌故事':'Create your collection'} enabledLocales={state.enabledLocales} locale={locale} navigation={state.navigation}/>},
 {key:'hero',node:<section className="yuva-hero">{s.showHeroVisual && <HeroPosterCarousel enabled={s.heroCarouselEnabled && s.heroCarouselAutoplay} slides={s.heroSlides} intervalSeconds={s.heroCarouselIntervalSeconds}/>}<div className="yuva-hero-copy"><p className="yuva-eyebrow">{t(s.heroKicker,locale)}</p><h1>{t(s.heroTitle,locale)}</h1><div className="yuva-hero-bottom"><p>{t(s.heroBody,locale)}</p><a className="yuva-button" href={`/${locale}/contact`}>{t(s.primaryCtaLabel,locale)} <span>↗</span></a></div></div><span className="yuva-image-note">{zh?'AI 概念彩妆大片':'Illustrative beauty campaign'}</span></section>},
 {key:'products',node:<section className="yuva-collections"><div className="yuva-section-label"><span>01 / {zh?'色彩篇章':'THE COLOR CHAPTERS'}</span><a href={`/${locale}/products`}>{zh?'探索全部':'Explore all'} ↗</a></div>{state.products.filter(p=>p.kind==='collection'||(!p.kind&&['lips','eyes','face'].includes(p.slug))).slice(0,3).map((p,i)=><a className="yuva-chapter" href={`/${locale}/products/${p.slug}`} key={p.slug}><img src={p.imageUrl} alt={t(p.name,locale)} loading="lazy"/><span className="yuva-chapter-index">0{i+1}</span><h2>{t(p.name,locale)}</h2><p>{t(p.summary,locale)}</p><span className="yuva-chapter-arrow">↗</span></a>)}<div className="yuva-featured"><h2>{zh?'精选产品':'Selected products'}</h2><div className="yuva-product-grid">{state.products.filter(p=>p.kind==='product'&&p.status==='published'&&p.featuredOnHome).slice(0,6).map(p=><a className="yuva-product-card" key={p.slug} href={`/${locale}/products/${p.slug}`}><img src={p.thumbnailUrl||p.imageUrl} alt={t(p.name,locale)} width="640" height="640" loading="lazy"/><h3>{t(p.name,locale)}</h3></a>)}</div></div></section>},
 {key:'factory',node:<section className="yuva-factories"><div className="yuva-section-label"><span>02 / {zh?'双地制造':'TWO MANUFACTURING BASES'}</span><a href={`/${locale}/pages/factories`}>{zh?'走近工厂':'Discover our locations'} ↗</a></div><div className="yuva-location-grid">{[['china','Jinhua, China','金华纤烁化妆品有限公司'],['indonesia','Indonesia','Yuvacosmetics']].map(([img,title,body])=><a className="yuva-location" key={img} href={`/${locale}/pages/factories#${img}`}><img src={A+img+'.webp'} alt={title+' — illustrative architectural concept'} loading="lazy"/><div><h3>{title}</h3><p>{body}</p><small>{zh?'工厂概念示意 · 非实景照片':'Illustrative concept · Not an actual site photograph'}</small></div></a>)}</div></section>},
 {key:'markets',node:<section className="yuva-manifesto"><span className="yuva-eyebrow">{zh?'您的构想，我们的协作':'YOUR VISION. OUR CRAFT.'}</span><h2>{zh?'从灵感，到品牌之作。':'From idea to iconic.'}</h2><p>{zh?'配方、色号与包装，一起定义您的下一款彩妆。':'Formula, shade and packaging. Let’s define what your next beauty collection could become.'}</p><a className="yuva-button" href={`/${locale}/pages/oem-odm`}>{zh?'探索 OEM / ODM':'Explore OEM / ODM'} ↗</a></section>},
 {key:'articles',node:<>{state.articles.filter(a=>a.status==='published'&&a.featuredOnHome).slice(0,s.homeArticleCount).map(a=><article className="yuva-journal" key={a.slug}><a href={`/${locale}/articles/${a.slug}`}><h2>{t(a.title,locale)}</h2><p>{t(a.excerpt,locale)}</p></a></article>)}</>},
 {key:'rfq',node:<section className="yuva-contact" id="rfq"><div><p className="yuva-eyebrow">{zh?'下一段色彩故事':'LET’S CREATE WHAT’S NEXT'}</p><h2>{zh?'开启您的\n美妆故事。':'Begin your\nbeauty story.'}</h2><p>{zh?'告诉我们产品方向、目标市场与定制需求。':'New ideas. New markets. A collection that feels like you.'}</p><a href={`/${locale}/pages/privacy`}>{zh?'询盘隐私说明':'Inquiry privacy'}</a></div><RfqForm locale={locale}/></section>}
 ];
 return <main className="yuva-site">{sections.filter(x=>s.visibleSections[x.key]).sort((a,b)=>s.sectionOrder[a.key]-s.sectionOrder[b.key]).map(x=><div key={x.key}>{x.node}</div>)}{s.customBlocks.filter(b=>b.enabled).sort((a,b)=>a.order-b.order).map(b=><section className="yuva-manifesto" key={b.id}><h2>{t(b.title,locale)}</h2><p>{t(b.body,locale)}</p>{b.mediaUrl&&<img src={b.mediaUrl} alt={t(b.title,locale)} loading="lazy"/>}</section>)}</main>;
}
