/* eslint-disable @next/next/no-img-element */
import type { ReactNode } from "react";
import { HomeNavigationShell } from "@/components/PublicSiteShell";
import { RfqForm } from "@/components/RfqForm";
import { t } from "@/lib/i18n";
import type { AdminState, HomeSectionKey, LocaleCode } from "@/types/site";

const asset = "/assets/current-template/";

export function ActiveTemplate({ locale, state }: { locale: LocaleCode; state: AdminState }) {
  const zh = locale === "zh";
  const settings = state.templateSettings;
  const categories = state.products.filter((product) => product.kind === "collection" && product.status === "published").slice(0, 3);
  const featured = state.products.filter((product) => product.kind === "product" && product.status === "published" && product.featuredOnHome).slice(0, settings.homeProductCount);
  const sections: { key: HomeSectionKey; node: ReactNode }[] = [
    { key: "navigation", node: <HomeNavigationShell brandName={state.siteSettings.title} ctaLabel={zh ? "联系询盘" : "Start a project"} enabledLocales={state.enabledLocales} locale={locale} navigation={state.navigation} /> },
    { key: "hero", node: <section className="dawn-hero"><div className="dawn-hero-copy"><p className="dawn-kicker">{t(settings.heroKicker, locale)}</p><h1>{t(settings.heroTitle, locale)}</h1><p>{t(settings.heroBody, locale)}</p><a className="dawn-button" href={`/${locale}/products`}>{zh ? "探索产品" : "Explore products"}<span aria-hidden="true">↗</span></a></div><div className="dawn-hero-image"><img src={settings.heroSlides.find((slide) => slide.enabled)?.imageUrl || `${asset}hero.jpg`} alt={zh ? "珍珠缎带蝴蝶结发饰" : "Pearl satin hair bow"} /></div></section> },
    { key: "products", node: <section className="dawn-section dawn-products"><div className="dawn-section-heading"><div><p className="dawn-kicker">{zh ? "探索系列" : "DISCOVER THE COLLECTION"}</p><h2>{zh ? "为下一组发饰寻找灵感。" : "Small details. Greater possibilities."}</h2></div><a className="dawn-text-link" href={`/${locale}/products`}>{zh ? "查看全部产品" : "View all products"} ↗</a></div><div className="dawn-category-grid">{categories.map((product) => <a className="dawn-category-card" key={product.slug} href={`/${locale}/products/${product.slug}`}><img src={product.imageUrl} alt={t(product.name, locale)} loading="lazy" /><div><h3>{t(product.name, locale)}</h3><span>↗</span></div></a>)}</div><div className="dawn-featured-heading"><h3>{zh ? "精选发饰" : "Selected accessories"}</h3><p>{zh ? "探索适合品牌系列的发饰搭配。" : "Explore hair accessories for a coordinated collection."}</p></div><div className="dawn-featured-grid">{featured.map((product) => <a className="dawn-featured-card" key={product.slug} href={`/${locale}/products/${product.slug}`}><img src={product.thumbnailUrl || product.imageUrl} alt={t(product.name, locale)} loading="lazy" /><h4>{t(product.name, locale)}</h4><span>{zh ? "查看产品" : "View details"} ↗</span></a>)}</div></section> },
    { key: "factory", node: <section className="dawn-oem"><div className="dawn-oem-copy"><p className="dawn-kicker">OEM / ODM</p><h2>{zh ? "从想法，到您的系列。" : "Your vision. A collection to make your own."}</h2><p>{zh ? "分享工具类型、材质、外观与包装构想，逐步确认可行方案。" : "Share your tool, material, finish and packaging ideas. Let’s define a brief together."}</p><a className="dawn-button" href={`/${locale}/pages/oem-odm`}>{zh ? "了解定制流程" : "Explore customization"}<span aria-hidden="true">↗</span></a></div><img src={`${asset}oem.jpg`} alt={zh ? "发饰定制设计工作台" : "Hair accessories design worktable"} loading="lazy" /></section> },
    { key: "markets", node: <section className="dawn-section dawn-story"><div className="dawn-section-heading"><div><p className="dawn-kicker">{zh ? "工艺与品质" : "MAKING & QUALITY"}</p><h2>{zh ? "关注产品的每一处细节。" : "Every detail matters."}</h2></div></div><div className="dawn-story-grid"><a href={`/${locale}/pages/factories`}><img src={`${asset}factory.jpg`} alt={zh ? "发饰组装" : "Hair accessory assembly"} loading="lazy"/><div><h3>{zh ? "制作流程" : "The making"}</h3><span>↗</span></div><p>{zh ? "了解发饰从选材到成品的关键环节。" : "Explore steps from materials to finished accessories."}</p></a><a href={`/${locale}/pages/research`}><img src={`${asset}quality.jpg`} alt={zh ? "珍珠发夹细节检查" : "Pearl hair clip inspection"} loading="lazy"/><div><h3>{zh ? "细节与质检" : "DETAILS / QUALITY"}</h3><span>↗</span></div><p>{zh ? "从材质、样品到验收标准逐项确认。" : "Discuss materials, samples and acceptance criteria."}</p></a></div></section> },
    { key: "articles", node: <section className="dawn-section dawn-about"><p className="dawn-kicker">LOFTYVISTA</p><h2>{zh ? "让每个细节，点亮品牌系列。" : "Beauty is in the details."}</h2><p>{zh ? "从发饰造型、佩戴体验到包装，每个细节都值得认真讨论。" : "From shape and feel to presentation, every detail deserves care."}</p><a className="dawn-text-link" href={`/${locale}/pages/about`}>{zh ? "了解更多" : "Our story"} ↗</a></section> },
    { key: "rfq", node: <section className="dawn-contact" id="rfq"><div><p className="dawn-kicker">{zh ? "开启对话" : "LET’S CREATE WHAT’S NEXT"}</p><h2>{zh ? "告诉我们您的构想。" : "Let’s make it yours."}</h2><p>{zh ? "提交发饰类别、目标市场、数量与外观需求。" : "Tell us about accessory types, destination market, quantity and desired look."}</p><small>{zh ? "" : ""}</small></div><RfqForm locale={locale}/></section> }
  ];
  return <main className="dawn-site">{sections.filter(({ key }) => settings.visibleSections[key]).sort((a, b) => settings.sectionOrder[a.key] - settings.sectionOrder[b.key]).map(({ key, node }) => <div key={key}>{node}</div>)}{settings.customBlocks.filter((block) => block.enabled).sort((a, b) => a.order - b.order).map((block) => <section className="dawn-section dawn-custom" key={block.id}><h2>{t(block.title, locale)}</h2><p>{t(block.body, locale)}</p>{block.mediaUrl && block.type === "image" ? <img src={block.mediaUrl} alt={t(block.title, locale)} loading="lazy" /> : null}{block.linkUrl ? <a className="dawn-button" href={block.linkUrl}>{(block.buttonLabel ? t(block.buttonLabel, locale) : (zh ? "了解更多" : "Learn more"))} ↗</a> : null}</section>)}</main>;
}
